-- Table: CUSTOMERS
-- Description: Stores customer profile and registration data
CREATE TABLE customers (
    customer_id       NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR2(100)   NOT NULL,
    first_name        VARCHAR2(50),
    last_name         VARCHAR2(50),
    registration_date DATE            DEFAULT SYSDATE,
    status            VARCHAR2(20)    DEFAULT 'active',
    created_date      DATE            DEFAULT SYSDATE,
    last_updated      DATE            DEFAULT SYSDATE,

    CONSTRAINT chk_customer_status CHECK (status IN ('active', 'inactive', 'suspended'))
);

-- Table: DATA_QUALITY_ERRORS
-- Description: Logs all data quality issues detected during ETL validation runs, with resolution tracking
CREATE TABLE data_quality_errors (
    error_id     NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name   VARCHAR2(100),
    column_name  VARCHAR2(100),
    error_type   VARCHAR2(100),
    error_value  VARCHAR2(4000),
    record_id    VARCHAR2(100),
    error_date   DATE            DEFAULT SYSDATE,
    resolved     CHAR(1)         DEFAULT 'N',

    CONSTRAINT chk_resolved CHECK (resolved IN ('Y', 'N'))
);

-- Table: ETL_AUDIT_LOG
-- Description: Tracks execution history of all ETL processes, including status, duration, and error details
CREATE TABLE etl_audit_log (
    log_id             NUMBER           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_name       VARCHAR2(100)    NOT NULL,
    step_name          VARCHAR2(100),
    status             VARCHAR2(20)     NOT NULL,
    records_processed  NUMBER           DEFAULT 0,
    error_message      CLOB,
    start_time         TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    end_time           TIMESTAMP,
    duration_seconds   NUMBER,

    CONSTRAINT chk_audit_status CHECK (status IN ('SUCCESS', 'ERROR', 'WARNING', 'STARTED'))
);

-- Table: PRODUCTS
-- Description: Stores product catalogue data including pricing and stock inventory levels
CREATE TABLE products (
    product_id      NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name    VARCHAR2(200)   NOT NULL,
    category        VARCHAR2(100),
    price           NUMBER(10,2),
    stock_quantity  NUMBER          DEFAULT 0,
    created_date    DATE            DEFAULT SYSDATE,
    last_updated    DATE            DEFAULT SYSDATE,

    CONSTRAINT chk_product_price          CHECK (price >= 0),
    CONSTRAINT chk_product_stock_quantity CHECK (stock_quantity >= 0)
);

-- Table: SALES_TRANSACTIONS
-- Description: Records all customer sales transactions, linking customers to products with pricing and payment details. Total amount is auto-calculated as a virtual column.
CREATE TABLE sales_transactions (
    transaction_id    NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       NUMBER          NOT NULL,
    product_id        NUMBER          NOT NULL,
    quantity          NUMBER          NOT NULL,
    unit_price        NUMBER(10,2)    NOT NULL,
    total_amount      NUMBER(10,2)    GENERATED ALWAYS AS (quantity * unit_price) VIRTUAL,
    transaction_date  DATE            DEFAULT SYSDATE,
    payment_method    VARCHAR2(50),
    created_date      DATE            DEFAULT SYSDATE,

    CONSTRAINT chk_sales_quantity    CHECK (quantity > 0),
    CONSTRAINT chk_sales_unit_price  CHECK (unit_price >= 0),

    CONSTRAINT fk_customer  FOREIGN KEY (customer_id)  REFERENCES customers (customer_id),
    CONSTRAINT fk_product   FOREIGN KEY (product_id)   REFERENCES products  (product_id)
);
